export const LAB_REPORT_PROMPT_TEXT = `You need to write a lab report in basic html no css is allowed cause your html will be rendered by a markdown editor. That means the layout needs to be semantic and accessible using only standard HTML elements. you might use align attribute.You need to write Theory, apparatus, make table of data with caption and heading , write calculation with the help of math latex and write discussion. From the provided pdf learn the theory , discussion , calulation patter and how you should compose the whole document . then learn from the style , patter, order from the pdf. then see the extra images of data and data tables . keep in mind you only learn from the pdf file dont copy data from there. you need to use data from the images provided to you. based on the provided data image you need to write calculation . also you need to create a table and calculation for least square fitting. like formula for getting slop and intersection etc and calulation for that. how to write calculation learn from those pdf and write calculation based on provided images. then write result and discussion on fidings. discussion should be short and concise. 3 point.Now there are two special tag you will use one is <math>latext code </math> . use this to write math equation . remeber only use to write equation . for multi line you may use multiple <math> with line break.

CHART TAG FORMAT (Support multiple datasets):
<chart data-datasets='[{"id":"ds1","xData":[1,2,3],"yData":[2,4,6],"model":"linear","label":"Dataset1"},{"id":"ds2","xData":[1,2,3],"yData":[1.5,3.5,5.5],"model":"linear","label":"Dataset2"}]' data-x-label="X" data-y-label="Y" data-width="100%" data-height="70vh" data-alignment="center"></chart>

CHART RULES:
1) Each dataset MUST have: id (unique string), xData (number array), yData (number array), model (fitting model), label (optional display name)
2) ALL datasets share SAME x-label and y-label
3) Supported models: linear, linear_y_mx, exponential, logarithmic, sine, cosine, tangent, power, logistic, polynomial, gaussian
4) Chart auto-computes least-squares fit for each dataset with its specified model
5) Multiple datasets are plotted together with different colors
6) You can have ONE or MANY datasets in a single chart

USAGE EXAMPLE:
- Single dataset: <chart data-datasets='[{"id":"exp1","xData":[5,10,15],"yData":[25,100,225],"model":"power"}]' data-x-label="Distance" data-y-label="Intensity"></chart>
- Multi dataset: Above example with 2 datasets of same X values

some extra info you must keep remeber,
1) THEORY always CONTAIN DRIVATION DEFINATION AND OVERAL DESCRIPTION
2) BEFORE GRAPH , GIVE H3 HEADER OF GRAPH
3) AFTER GRAPH GIVE ITALIC HEADER OF FIGURE 2, LIKE DESCRIPTION
`;

export const COVER_TEMPLATES = {
  'M-012': `<h2 style="text-align: center; font-size: 30px; font-weight: 700; color: black; display: block; margin: 0.4em 0px;">Lab Report</h2><p style="text-align: center;"></p><h3 style="text-align: left; font-size: 24px; font-weight: 700; color: black; display: block; margin: 0.3em 0px;"><em><u>Experiment name:  </u></em></h3><h4 style="text-align: left; font-size: 20px; font-weight: 700; color: black; display: block; margin: 0.2em 0px;"><strong><em><u>jkjkjkasjdfkjadsfjkasdkfjasdfkjasdfjaskdljfkl;sdjflkasdjfklsdjfsdjfksdjfsldjfklsdjfklsdajflsdjfk</u></em></strong></h4><p style="text-align: left;"></p><p style="text-align: left;"></p><h3 style="text-align: left; font-size: 24px; font-weight: 700; color: black; display: block; margin: 0.3em 0px;"><em><u>Experiment Number :</u>   O5</em></h3><h3 style="text-align: left; font-size: 24px; font-weight: 700; color: black; display: block; margin: 0.3em 0px;"><em><u>Experiment Date:</u>  02/02/2026</em></h3><h3 style="text-align: left; font-size: 24px; font-weight: 700; color: black; display: block; margin: 0.3em 0px;"><em><u>Name</u>: Md. Mobin Chowdhury</em></h3><h3 style="text-align: left; font-size: 24px; font-weight: 700; color: black; display: block; margin: 0.3em 0px;"><em><u>Roll</u>: FH-118-012</em></h3><h3 style="text-align: left; font-size: 24px; font-weight: 700; color: black; display: block; margin: 0.3em 0px;"><em><u>Lab</u> Group: C</em></h3><h3 style="text-align: left; font-size: 24px; font-weight: 700; color: black; display: block; margin: 0.3em 0px;"><em><u>Batch</u> : 05</em></h3><h3 style="text-align: left; font-size: 24px; font-weight: 700; color: black; display: block; margin: 0.3em 0px;"><em><u>Session</u>: 2023-24</em></h3><h3 style="text-align: left; font-size: 24px; font-weight: 700; color: black; display: block; margin: 0.3em 0px;"><em><u>Date of Submission</u>: 30/04/2026</em></h3>`,
  'S-60': `<h2 style="text-align: center; font-size: 30px; font-weight: 700; color: black; display: block; margin: 0.4em 0px;"><strong>University of Dhaka</strong></h2><h2 style="text-align: center; font-size: 30px; font-weight: 700; color: black; display: block; margin: 0.4em 0px;"><strong>Department of Physics</strong></h2><h3 style="text-align: center; font-size: 24px; font-weight: 700; color: black; display: block; margin: 0.3em 0px;"><strong>Lab Report</strong></h3><p style="text-align: center;"></p><h3 style="text-align: left; font-size: 24px; font-weight: 700; color: black; display: block; margin: 0.3em 0px;"><strong><em><u>Experiment name:  </u></em></strong></h3><h4 style="text-align: left; font-size: 20px; font-weight: 700; color: black; display: block; margin: 0.2em 0px;"><strong><em><u>jkjkjkasjdfkjadsfjkasdkfjasdfkjasdfjaskdljfkl;sdjflkasdjfklsdjfsdjfksdjfsldjfklsdjfklsdajflsdjfk</u></em></strong></h4><h3 style="text-align: left; font-size: 24px; font-weight: 700; color: black; display: block; margin: 0.3em 0px;"></h3><h3 style="text-align: left; font-size: 24px; font-weight: 700; color: black; display: block; margin: 0.3em 0px;"><strong><em><u>Experiment Number :</u>   O5</em></strong></h3><h3 style="text-align: left; font-size: 24px; font-weight: 700; color: black; display: block; margin: 0.3em 0px;"><strong><em><u>Experiment Date:</u>  02/02/2025</em></strong></h3><h3 style="text-align: left; font-size: 24px; font-weight: 700; color: black; display: block; margin: 0.3em 0px;"></h3><h3 style="text-align: center; font-size: 24px; font-weight: 700; color: black; display: block; margin: 0.3em 0px;"><strong><em>Submitted by:</em></strong></h3><h3 style="text-align: left; font-size: 24px; font-weight: 700; color: black; display: block; margin: 0.3em 0px;"></h3><h3 style="text-align: left; font-size: 24px; font-weight: 700; color: black; display: block; margin: 0.3em 0px;"><em>     Name: Md. Sadik Hossen</em></h3>`,
  'R-66': `<h2 style="text-align: center; font-size: 30px; font-weight: 700; color: black; display: block; margin: 0.4em 0px;">Lab Report</h2><p style="text-align: center;"></p><h3 style="text-align: left; font-size: 24px; font-weight: 700; color: black; display: block; margin: 0.3em 0px;"><em><u>Name of Experiment:  </u></em></h3><h4 style="text-align: left; font-size: 20px; font-weight: 700; color: black; display: block; margin: 0.2em 0px;"><strong><em><u>jkjkjkasjdfkjadsfjkasdkfjasdfkjasdfjaskdljfkl;sdjflkasdjfklsdjfsdjfksdjfsldjfklsdjfklsdajflsdjfk</u></em></strong></h4><p style="text-align: left;"></p><p style="text-align: left;"></p><h3 style="text-align: left; font-size: 24px; font-weight: 700; color: black; display: block; margin: 0.3em 0px;"><em><u>Number of Experiment :</u>   O5</em></h3><h3 style="text-align: left; font-size: 24px; font-weight: 700; color: black; display: block; margin: 0.3em 0px;"><em><u>Date of Experiment :</u>  02/02/2026</em></h3><h2 style="text-align: center; font-size: 30px; font-weight: 700; color: black; display: block; margin: 0.4em 0px;"><em>Submitted By</em></h2><p style="text-align: center;"></p><h3 style="text-align: left; font-size: 24px; font-weight: 700; color: black; display: block; margin: 0.3em 0px;"><em><u>Name</u>: Raisa Alam</em></h3><h3 style="text-align: left; font-size: 24px; font-weight: 700; color: black; display: block; margin: 0.3em 0px;"><em><u>Roll</u>: SK-118-066</em></h3><h3 style="text-align: left; font-size: 24px; font-weight: 700; color: black; display: block; margin: 0.3em 0px;"><em><u>Lab</u> Group: C</em></h3><h3 style="text-align: left; font-size: 24px; font-weight: 700; color: black; display: block; margin: 0.3em 0px;"><em><u>Batch</u> : 05</em></h3><h3 style="text-align: left; font-size: 24px; font-weight: 700; color: black; display: block; margin: 0.3em 0px;"><em><u>Session</u>: 2023-24</em></h3>`,
};
